# Generated by Django 6.0.2 on 2026-02-18 16:06

import app.models
import ckeditor_uploader.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyPortfolio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('currency', models.CharField(default='USD, KES', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price per person', max_digits=10)),
                ('duration_days', models.PositiveIntegerField(default=0)),
                ('duration_nights', models.PositiveIntegerField(default=0)),
                ('includes', models.CharField(help_text='Hot air balloon included', max_length=255)),
                ('tags', models.CharField(help_text='Ultimate Safari or Cruise Exclusive', max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('main_image', models.ImageField(upload_to=app.models.upload_image_to)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'News',
            },
        ),
    ]
