# Generated by Django 6.0.2 on 2026-02-18 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legacyportfolio',
            options={'verbose_name_plural': 'LegacyPortfolio'},
        ),
        migrations.AddField(
            model_name='legacyportfolio',
            name='duration_hours',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
