# Generated by Django 6.0.2 on 2026-02-21 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_legacyportfolio_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='legacyportfolio',
            name='published_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
