# Generated by Django 6.0.2 on 2026-02-21 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_legacyportfolio_published_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='legacyportfolio',
            old_name='published_date',
            new_name='date',
        ),
    ]
