# Generated by Django 6.0.2 on 2026-02-23 16:57

import app.models
import ckeditor_uploader.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_published_date_legacyportfolio_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CulturalImmersions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price per person', max_digits=10)),
                ('season', models.CharField(help_text='eg. July - October', max_length=255)),
                ('community_impact', models.CharField(help_text='Supports Swahili artisan cooperatives and heritage preservation', max_length=255)),
                ('includes', models.CharField(help_text='6 days, luxury mobile camp, Maasai cultural immersion', max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('main_image', models.ImageField(upload_to=app.models.upload_image_to)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'CulturalImmersion',
            },
        ),
    ]
