# Generated by Django 6.0.2 on 2026-02-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_culturalimmersions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culturalimmersions',
            name='includes',
            field=models.TextField(help_text='6 days, luxury mobile camp, Maasai cultural immersion'),
        ),
        migrations.AlterField(
            model_name='legacyportfolio',
            name='includes',
            field=models.TextField(help_text='Hot air balloon included'),
        ),
    ]
