# Generated by Django 6.0.2 on 2026-03-20 09:27

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='about',
            field=models.CharField(default='none', help_text='eg. Conservation or Eco-Travel', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='cover_image',
            field=models.ImageField(help_text='Recommended size: 1200×630px.', upload_to=app.models.upload_image_to),
        ),
        migrations.AlterField(
            model_name='blog',
            name='excerpt',
            field=models.TextField(help_text='Short summary shown on listing cards (max 300 chars).', max_length=300),
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
    ]
