# Generated by Django 6.0.2 on 2026-03-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_blog_about_alter_blog_cover_image_alter_blog_excerpt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='excerpt',
            field=models.TextField(help_text='Short summary shown on listing cards (max 200 chars).', max_length=200),
        ),
    ]
